CREATE TABLE EQUIPAGGI( 
Codice CHAR(10), 
Nome VARCHAR(30) NOT NULL, 
Cognome VARCHAR(30) NOT NULL, 
Ruolo VARCHAR(30) NOT NULL, 
CONSTRAINT PK_EQUIPAGGI PRIMARY KEY(Codice) 
);
 
CREATE TABLE MISSIONI( 
Codice CHAR(10), 
Data_inizio DATE NOT NULL, 
Data_fine DATE, 
Stato VARCHAR(11) NOT NULL, 
Tipologia VARCHAR(22) NOT NULL, 
CONSTRAINT PK_MISSIONI PRIMARY KEY(Codice), 
CONSTRAINT CK_STATO_MISSIONI CHECK(Stato='Pianificata' OR Stato='In Corso' OR Stato='Completata' OR Stato='Annullata'), 
CONSTRAINT CK_TIPOLOGIA_MISSIONI CHECK(Tipologia='Mappatura Geologica' OR Tipologia='Rilevamento di Risorse') 
);

CREATE TABLE ROBOT( 
ID NUMBER, 
Tipologia VARCHAR(20) NOT NULL, 
CONSTRAINT PK_ROBOT PRIMARY KEY(ID) 
);

CREATE TABLE SENSORI( 
ID NUMBER, 
Tipologia VARCHAR(11) NOT NULL, 
Data_last_check DATE NOT NULL, 
Data_installazione DATE NOT NULL, 
Stato VARCHAR(14) NOT NULL, 
Latitudine VARCHAR(20) NOT NULL, 
Longitudine VARCHAR(20) NOT NULL, 
Altitudine VARCHAR(20) NOT NULL, 
CONSTRAINT PK_SENSORI PRIMARY KEY(ID), 
CONSTRAINT CK_TIPOLOGIA_SENSORI CHECK(Tipologia='Temperatura' OR Tipologia='Pressione' OR Tipologia='Gas' OR Tipologia='Radiazioni' OR Tipologia='Geologia'), 
CONSTRAINT CK_STATO_SENSORI CHECK(Stato='Attivo' OR Stato='Stand-By' OR Stato='Manutenzione' OR Stato='Malfunzionante') 
);

CREATE TABLE RILEVAZIONI( 
Codice NUMBER, 
Data_ora DATE NOT NULL, 
Valore NUMBER NOT NULL, 
Sensore NUMBER NOT NULL, 
CONSTRAINT PK_RIVELAZIONI PRIMARY KEY(Codice) 
);

CREATE TABLE ANOMALIE( 
Codice NUMBER, 
Data_ora DATE NOT NULL, 
Priorita VARCHAR(7) NOT NULL, 
Causa CLOB NOT NULL, 
Sensore NUMBER NOT NULL, 
CONSTRAINT PK_ANOMALIE PRIMARY KEY(Codice), 
CONSTRAINT CK_PRIORITA CHECK(Priorita='Bassa' OR Priorita='Media' OR Priorita='Alta' OR Priorita='Critica') 
);

CREATE TABLE INTERVENTI( 
Codice NUMBER, 
Descrizione VARCHAR(100) NOT NULL, 
Data_esecuzione DATE NOT NULL, 
Esito VARCHAR(30), 
Anomalia NUMBER NOT NULL, 
CONSTRAINT PK_INTERVENTI PRIMARY KEY(Codice) 
);

CREATE TABLE REPORT( 
Codice VARCHAR(10), 
Titolo VARCHAR(15) NOT NULL, 
Descrizione CLOB NOT NULL, 
Data_ora DATE NOT NULL, 
Equipaggio CHAR(10) NOT NULL, 
Missione CHAR(10) NOT NULL, 
CONSTRAINT PK_REPORT PRIMARY KEY(Codice) 
);

CREATE TABLE EQUIPAGGIMISSIONI( 
Equipaggio CHAR(10), 
Missione CHAR(10), 
CONSTRAINT PK_EQUIPAGGIMISSIONI PRIMARY KEY(Equipaggio, Missione) 
);

CREATE TABLE ROBOTMISSIONI( 
Robot NUMBER, 
Missione CHAR(10), 
CONSTRAINT PK_ROBOTMISSIONI PRIMARY KEY(Robot, Missione) 
);

CREATE TABLE SENSORIMISSIONI( 
Sensore NUMBER, 
Missione CHAR(10), 
CONSTRAINT PK_SENSORIMISSIONI PRIMARY KEY(Sensore, Missione) 
);

CREATE TABLE EQUIPAGGIINTERVENTI( 
Equipaggio CHAR(10), 
Intervento NUMBER, 
CONSTRAINT PK_EQUIPAGGIINTERVENTI PRIMARY KEY(Equipaggio, Intervento) 
);

ALTER TABLE RILEVAZIONI ADD CONSTRAINT FK_RILEVAZIONI_SENSORI FOREIGN KEY(Sensore) REFERENCES Sensori(ID);

ALTER TABLE ANOMALIE ADD CONSTRAINT FK_ANOMALIE_SENSORI FOREIGN KEY(Sensore) REFERENCES Sensori(ID);

ALTER TABLE INTERVENTI ADD CONSTRAINT FK_INTERVENTI_ANOMALIE FOREIGN KEY(Anomalia) REFERENCES Anomalie(Codice);

ALTER TABLE REPORT ADD CONSTRAINT FK_REPORT_EQUIPAGGI FOREIGN KEY(Equipaggio) REFERENCES Equipaggi(Codice);

ALTER TABLE REPORT ADD CONSTRAINT FK_REPORT_MISSIONI FOREIGN KEY(Missione) REFERENCES Missioni(Codice);

ALTER TABLE EQUIPAGGIMISSIONI ADD CONSTRAINT FK_EQUIPAGGIMISSIONI_EQUIPAGGI FOREIGN KEY(Equipaggio) REFERENCES Equipaggi(Codice);

ALTER TABLE EQUIPAGGIMISSIONI ADD CONSTRAINT FK_EQUIPAGGIMISSIONI_MISSIONI FOREIGN KEY(Missione) REFERENCES Missioni(Codice);

ALTER TABLE ROBOTMISSIONI ADD CONSTRAINT FK_ROBOTMISSIONI_ROBOT FOREIGN KEY(Robot) REFERENCES Robot(ID);

ALTER TABLE ROBOTMISSIONI ADD CONSTRAINT FK_ROBOTMISSIONI_MISSIONI FOREIGN KEY(Missione) REFERENCES Missioni(Codice);

ALTER TABLE SENSORIMISSIONI ADD CONSTRAINT FK_SENSORIMISSIONI_SENSORI FOREIGN KEY(Sensore) REFERENCES Sensori(ID);

ALTER TABLE SENSORIMISSIONI ADD CONSTRAINT FK_SENSORIMISSIONI_MISSIONI FOREIGN KEY(Missione) REFERENCES Missioni(Codice);

ALTER TABLE EQUIPAGGIINTERVENTI ADD CONSTRAINT FK_EQUIPAGGIINTERVENTI_EQUIPAGGI FOREIGN KEY(Equipaggio) REFERENCES Equipaggi(Codice);

ALTER TABLE EQUIPAGGIINTERVENTI ADD CONSTRAINT FK_EQUIPAGGIINTERVENTI_INTERVENTI FOREIGN KEY(Intervento) REFERENCES Interventi(Codice);

